### ISSUE TITLE
Failed YFT import - Shader 'glass_emissivenight_alpha' does not exist!

### ISSUE THREAD

**Issue by MoravianLion** [Skylumz/Sollumz#399] opened 2022-09-02 13:19 UTC
When trying to import "prop_streetlight_06", Blender throw in following error

`
Error importing: C:\Users\MoravianLion\Desktop\Blender\sort out\gta_lights\prop_streetlight_06.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\sollumz_operators.py", line 71, in import_file
    import_yft(filepath, self.import_settings)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\yft\yftimport.py", line 249, in import_yft
    fragment_to_obj(yft_xml, filepath, import_settings)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\yft\yftimport.py", line 192, in fragment_to_obj
    materials = shadergroup_to_materials(
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 21, in shadergroup_to_materials
    material = create_shader(shader.name, shader.filename)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 718, in create_shader
    raise AttributeError(f"Shader '{name}' does not exist!")
AttributeError: Shader 'glass_emissivenight_alpha' does not exist!

`

Edit.: Problem was due to importing NVE version of the said prop.

When adding vanilla prop, the error changes to following

Error importing: C:\Users\MoravianLion\Desktop\Blender\sort out\gta_lights\prop_streetlight_06.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\sollumz_operators.py", line 71, in import_file
    import_yft(filepath, self.import_settings)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\yft\yftimport.py", line 249, in import_yft
    fragment_to_obj(yft_xml, filepath, import_settings)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Sollumz-main\yft\yftimport.py", line 229, in fragment_to_obj
    bone_index = child.parent.data.bones[parent_bone].bone_properties.tag
KeyError: 'bpy_prop_collection[key]: key "Root_Prop_Worklight_01A_frag_" not found'

**Comment by CFox04** [comment] 2022-09-02 17:25
Duplicate of #373

**Closed** 2022-09-02 17:25 UTC
