### ISSUE TITLE
Terrain Painter is not working

### ISSUE THREAD

**Issue by MARIO228** [Skylumz/Sollumz#277] opened 2022-03-05 23:39 UTC
Using latest version of sollumz and when pressing on Paint Texture1/Paint Texture2/Paint Texture3/Paint Texture4 doesn't change color of the brush
![blender_ULdb9KLUKz](https://user-images.githubusercontent.com/40245545/156903231-716fe342-317e-4bc8-bacd-2019c996dd26.gif)

And if i change color of the brush by myself and paint terrain, it doesn't change it if you look at it in material preview
![image](https://user-images.githubusercontent.com/40245545/156903255-320845ad-338d-44e6-8208-5e59856b3851.png)
![image](https://user-images.githubusercontent.com/40245545/156903256-13f073e2-6655-49ee-9193-b48023d07bb0.png)

textures
![image](https://user-images.githubusercontent.com/40245545/156903257-3395a283-30f0-4916-a3d1-7b6aca8fbbed.png)

shader
![image](https://user-images.githubusercontent.com/40245545/156903262-057d30bd-b7df-4468-b06d-95542c06faad.png)
![image](https://user-images.githubusercontent.com/40245545/156903264-ce2bb7d0-8c36-4187-9f54-ffd9a5ee3045.png)

result (don't mind the placement)
![image](https://user-images.githubusercontent.com/40245545/156903272-688bbc94-8a6c-405e-8820-d6d548439bf6.png)

**Comment by MARIO228** [comment] 2022-03-06 10:23
UPD. Needed to change to terrain brush, but still doesn't change with what texture i wanna paint it, may be still doing something wrong, but there was no explanation on that.

**Comment by CFox04** [comment] 2022-03-20 14:49
Gonna close this now if you have a new different problem feel free to make a new issue.

**Closed by CFox04** 2022-03-20 14:49 UTC

**Comment by DragonEyeDesigns** [comment] 2022-11-23 15:16
I have reached the same point as mentioned above except the textures are mixing together as intended in Blender.
However the resulting YDR only has the primary texture applied to it in Codewalker.
I have tried using embedded and non-embedded textures.
