### ISSUE TITLE
Having a problem with exporting anim

### ISSUE THREAD

**Issue by Drenchanim** [Skylumz/Sollumz#914] opened 2024-06-04 22:41 UTC
![Screenshot_11](https://github.com/Skylumz/Sollumz/assets/171747094/ee63e28f-37a3-4803-b866-0bc83da952ac)
im getting this from trying to export my animation if i can get assist please in thank you

**Comment by alexguirre** [comment] 2024-06-12 20:29
Duplicate of #887.

**Closed by alexguirre** 2024-06-12 20:29 UTC
