### ISSUE TITLE
Import error : 'NoneType' object has no attribute 'from_xml'

### ISSUE THREAD

**Issue by Minibull3** [Skylumz/Sollumz#584] opened 2023-03-01 22:56 UTC
Hello !
A Sollumz user have this error when he try to import this ymap : hei_po1_07_long_0.ymap
He use the lasted sollumz version from github and 3.4 blender version :
![image](https://user-images.githubusercontent.com/119362041/222283451-35f9c0c8-f6fb-42f4-81be-7e5b49ed8b5a.png)

i tried to reproduce and i have the same issue (but i have blender 3.3 and not the lasted sollumz update).
Note that it doesnt mater if we export this ymap with RPF explorer or OpenIV (i tried with openIV just in case), the error is the same, we cant import it  : 
![image](https://user-images.githubusercontent.com/119362041/222285008-328479dd-f354-4792-9c83-b670fd8f2891.png)

it's the 1st time i see this error.

Thx for your help !

**Comment by Minibull3** [comment] 2023-03-01 23:12
here the ymap .xml if it can help

[hei_po1_07_long_0.ymap.zip](https://github.com/Skylumz/Sollumz/files/10866056/hei_po1_07_long_0.ymap.zip)

**Comment by coltfox** [comment] 2023-03-02 15:21
Fixed in 242b3ac6bbdcbe7c3f0115c1cc5af527f1950040. This issue was caused by the ymap containing an unknown extension type called 'rage__phVerletClothCustomBounds'. It now skips unknown extensions so the 'rage__phVerletClothCustomBounds' extension in this ymap will be lost on import/export until someone implements it into Sollumz.

**Closed by coltfox** 2023-03-02 15:21 UTC
