### ISSUE TITLE
Blender crashes when importing models as assets

### ISSUE THREAD

**Issue by mnsb223** [Skylumz/Sollumz#771] opened 2023-09-18 03:33 UTC
Blender crashes randomly whenever you import any YDR/YFT as an asset.

**Comment by alexguirre** [comment] 2023-09-18 10:30
Do you have any more information to reproduce the crash? It is not crashing for me.

**Comment by mnsb223** [comment] 2023-09-18 16:14
Genuinely I don't. It hard crashes, no error messages, nothing.

**Comment by alexguirre** [comment] 2023-09-18 18:12
Which version of Sollumz are you using?

**Comment by mnsb223** [comment] 2023-09-18 21:05
Version 2.1

**Comment by alexguirre** [comment] 2023-10-07 18:43
Cannot reproduce these crashes, closing for now.

**Closed by alexguirre** 2023-10-07 18:43 UTC
Labels: investigate
