### ISSUE TITLE
Importing yft's not responding till i close it with task manager

### ISSUE THREAD

**Issue by RealMrCactus** [Skylumz/Sollumz#927] opened 2024-07-10 19:57 UTC
when i try importing a yft it just doesnt respond until i kill it with task manager

**Comment by ook3D** [comment] 2024-07-10 23:09
> when i try importing a yft it just doesnt respond until i kill it with task manager

Can you send the original yfts

**Comment by alexguirre** [comment] 2024-07-11 08:58
Possibly same issue as #862. It is fixed but not released yet so you can try installing the latest commit.

**Comment by RealMrCactus** [comment] 2024-07-12 04:13
> > when i try importing a yft it just doesnt respond until i kill it with task manager
> 
> Can you send the original yfts

it was ripples valor i needed models so i could texture in substance

**Comment by ook3D** [comment] 2024-07-12 05:20
> > > when i try importing a yft it just doesnt respond until i kill it with task manager
> > 
> > 
> > Can you send the original yfts
> 
> it was ripples valor i needed models so i could texture in substance

not really sure what 'ripples valor' is, can you link it?

**Comment by alexguirre** [comment] 2024-07-19 22:23
Can't fix anything if we can't reproduce it. Anyway, as I mentioned, this is probably a duplicate of #862. Try installing the latest commit (not release) that includes the fix and import again.

**Closed by alexguirre** 2024-07-19 22:23 UTC
