### ISSUE TITLE
Crashing when importing multiple files as assets

### ISSUE THREAD

**Issue by Mellowtri** [Skylumz/Sollumz#753] opened 2023-09-11 16:01 UTC
If I try to import more than 1 file as an asset at a time, its 50/50 if blender crashes or not. No error message or anything, just closes down.
One attempt I was able to import 36 files as assets fine, I then restarted blender and tried to import the same 36 assets again, this time it just kept crashing. I tried with low numbers all the way down to 3 at a time, sometimes it would work, but mainly it would just close down.
Never had an issue with just a single asset, so mainly seems to be an issue with multiple ones.

There's also the issue of the assets not showing up with textures in the library. When you drag them into the scene, the textures appear fine, but never updates in the library.

I'm on Blender 3.5.1

**Comment by Hancapo** [comment] 2023-09-11 17:04
It should work without crashes in Sollumz 2.0

**Comment by Mellowtri** [comment] 2023-09-11 17:12
I'm on 2.0, I even updated sollumz version yesterday from latest github version.

**Comment by alexguirre** [comment] 2023-10-07 18:43
Cannot reproduce these crashes, closing for now.

**Closed by alexguirre** 2023-10-07 18:43 UTC
