### ISSUE TITLE
Can't import grass with ymap position on terrain

### ISSUE THREAD

**Issue by MichaelWengren** [Skylumz/Sollumz#924] opened 2024-06-29 02:06 UTC
I've imported terrain mesh ch2_03d_l2.ydr with it's ymap and archetypes, as well as ch2_03_grass_0.ymap and all grass meshes from x64i.rpf\levels\gta5\props\procedural\v_proc1.rpf for terrain and no foliage assets was placed on terrain in Blender. 
Is there a way to place all grass meshes on the terrain like it was in the game?

**Comment by ook3D** [comment] 2024-06-29 03:20
this is because they arent simply just grass entities, but 'Grass Batches', which is not implemented yet

**Comment by ook3D** [comment] 2024-06-29 22:40
> @ook3D but these grass batches are made up of simple mesh pieces, there are special ymaps for grass with positional data, and it should work the same as with any other mesh.
> Where there any major roadblock to implement grass batched in Sollumz? 

Look at the xml of the ymap, it's not the same as a normal one, and it's not that there's a roadblock, just not really enough time for those who are capable to implement it

**Comment by alexguirre** [comment] 2024-06-29 23:07
Duplicate of #782.

**Closed by alexguirre** 2024-06-29 23:07 UTC
