### ISSUE TITLE
Lod + ymap import (incorrect rotation)

### ISSUE THREAD

**Issue by FilipeCuco** [Skylumz/Sollumz#720] opened 2023-08-20 22:20 UTC
when I import a lod and then the ymap the rotation of that object looks like this

ymap:
lr_sc1_02

model:
lr_sc1_02_slod1_children

![image](https://github.com/Skylumz/Sollumz/assets/116587926/df672367-1d7f-446a-a4d8-f03389c3fa68)

**Comment by alexguirre** [comment] 2023-08-20 23:19
Might be related to #704.

**Comment by alexguirre** [comment] 2023-08-21 21:48
Duplicate of #704.

**Closed by alexguirre** 2023-08-21 21:48 UTC
Labels: bug
