### ISSUE TITLE
Sollumz Not Functional 

### ISSUE THREAD

**Issue by forbesee1** [Skylumz/Sollumz#36] opened 2021-09-30 16:18 UTC
Do we have a update on the refractor? In its current state this sadly doesn't work - do we have a previous version that works with blender?

**Comment by soryy708** [comment] 2021-10-01 17:20
Duplicate of https://github.com/Skylumz/Sollumz/issues/35 ?

**Comment by Skylumz** [comment] 2021-10-04 04:18
"Doesn't work" does not help me I need useful information what doesn't work. You can join the codewalker server to stay updated! https://discord.gg/BxfKHkk

**Closed by Skylumz** 2021-10-04 04:18 UTC
